export const OfferFieldProps = {
  MIN_TITLE_LENGTH: 10,
  MAX_TITLE_LENGTH: 100,
  MIN_DESCRIPTION_LENGTH: 20,
  MAX_DESCRIPTION_LENGTH: 1024,
  IMAGES_COUNT: 6,
  MIN_BEDROOMS: 1,
  MAX_BEDROOMS: 8,
  MIN_ADULTS: 1,
  MAX_ADULTS: 10,
  MIN_PRICE: 100,
  MAX_PRICE: 100000,
  MIN_GOODS: 1,
};
